repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        stages:
        - commit
        - push
    -   id: end-of-file-fixer
        stages:
        - commit
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
        stages:
        - commit
        - push
    -   id: debug-statements
        stages:
        - commit
        - push
    -   id: requirements-txt-fixer
        stages:
        - commit
        - push
        args:
        - requirements.txt
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    -   id: add-trailing-comma
        stages:
        - commit
        - push
